const express = require('express')
const path = require('path')
const app = express()
const { PORT } = require('./config')
const createConnection = require('./database/index.js')
const apiRouter = require('./routes/api')

app.use('/client', express.static(path.resolve(__dirname, './client')))
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use('/api', apiRouter)

createConnection()
	.then(() => app.listen(PORT, () => console.log(`Server has been started on port ${PORT}...`)))
	.catch(err => console.log('Error: ', JSON.stringify(err)))